from setuptools import setup

setup(
    name='gemini-python',
    version='0.3.0',
    packages=['gemini'],
    url='https://github.com/TheTallMan67/gemini-python',
    license='MIT',
    author='Mohammad Usman',
    author_email='m.t.usman@hotmail.com',
    description='A python client for the Gemini API and Websocket',
    python_requires='>=3',
    install_requires=['requests', 'pytest'],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    keywords=['gemini', 'bitcoin', 'bitcoin-exchange', 'ethereum', 'ether', 'BTC', 'ETH', 'gemini-exchange'],
)
